version: '3.8'

services:
  vaultsync:
    build: .
    container_name: vaultsync_server
    restart: unless-stopped
    ports:
      - "5436:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=vaultsync
      - DB_USER=vaultsync
      - DB_PASS=vaultsync_secure_password
      - VAULTSYNC_SECRET=63f4945d921d599f27ae4fdf5bada3f1
    volumes:
      - ./storage:/app/storage
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: vaultsync_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vaultsync
      - POSTGRES_USER=vaultsync
      - POSTGRES_PASSWORD=vaultsync_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
